### ISSUE TITLE
hit an error in both branch iso and master

### ISSUE THREAD

**Issue by TurBoss** [bitcraft/pyscroll#10] opened 2015-11-09 05:10 UTC
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    game.main()
  File "main.py", line 85, in main
    self.update(dt)
  File "main.py", line 55, in update
    self.levelGroup.update(dt)
  File "/home/jauria/Proyectos/IsoGame/pyscroll/util.py", line 90, in update
    pygame.sprite.LayeredUpdates.update(self, dt)
  File "/usr/lib/python2.7/dist-packages/pygame/sprite.py", line 399, in update
    for s in self.sprites(): s.update(*args)
TypeError: update() takes exactly 1 argument (2 given)

got this error in windows xp (Master branch) and linux (Isometric branch)

not sure if a bug or my fault
thx

**Comment by TurBoss** [comment] 2015-11-09 05:12
windows tests were made using the pip version

**Comment by TurBoss** [comment] 2015-11-09 05:20
if I comment the update function i get the following error:

  File "main.py", line 47, in draw
    self.levelGroup.center(self.player.rect.center)
  File "/home/jauria/Proyectos/IsoGame/pyscroll/util.py", line 99, in center
    self._map_layer.center(value)
  File "/home/jauria/Proyectos/IsoGame/pyscroll/pyscroll.py", line 611, in center
    self.redraw()
  File "/home/jauria/Proyectos/IsoGame/pyscroll/pyscroll.py", line 619, in redraw
    self.flush()
  File "/home/jauria/Proyectos/IsoGame/pyscroll/pyscroll.py", line 230, in flush
    self.blit_tiles(self.queue)
  File "/home/jauria/Proyectos/IsoGame/pyscroll/pyscroll.py", line 568, in blit_tiles
    blit(tile, (xxx, yyy))
TypeError: argument 1 must be pygame.Surface, not tuple

**Comment by bitcraft** [comment] 2015-11-09 05:23
Thanks for the report.  Could you paste or link more of the code you are using?  specifically, how you are building the renderer and sprite group?  Thanks

**Comment by TurBoss** [comment] 2015-11-09 05:30
main.py : http://dpaste.com/2A0N774
level.py : http://dpaste.com/367DB60
player.py : http://dpaste.com/1992CM9

data files can be found in http://dpaste.com/1992CM9

thx

**Comment by TurBoss** [comment] 2015-11-09 05:32
I'm sure that i'm doing something wrong :)

**Comment by bitcraft** [comment] 2015-11-09 22:18
I was unable to reproduce your problem.  Could you make sure the code in your repo is current?  Thanks!

**Comment by TurBoss** [comment] 2015-11-09 22:37
the code is in the Dpaste urls the repo does not contain the pyscroll stuff yet
sry for the confusion :)

**Comment by TurBoss** [comment] 2015-11-14 01:17
Sry the dpaste code has the lines commented :P 
here is the latest https://github.com/TurBoss/IsoGame

**Comment by bitcraft** [comment] 2015-11-24 02:27
Thanks for updating that.  I'm going to bring that isometric branch up to date and try again.  I have just a couple comments.  Please investigate linting tools, an IDE, or tools like autopep8.  The code is kinda messy and difficult to find things.

**Comment by bitcraft** [comment] 2015-11-25 07:11
I've got some progress tonight.  I'll see what I can do later this week.

https://gyazo.com/d2c7e39774090a33957b09bc3274479a

**Comment by TurBoss** [comment] 2015-11-26 02:36
thank you i will test tonight

**Comment by bitcraft** [comment] 2015-12-24 14:43
I'm going to close this issue as it is a duplicate of #4.  If you have more comments about the isometric render, please direct them to issue #4.  Thanks!

**Closed by bitcraft** 2015-12-24 14:43 UTC
